# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheModel',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('details', models.CharField(max_length=5000)),
            ],
        ),
    ]
